/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-07-13 03:58:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AjaxJs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.tlweb.*;

public final class ReturnService_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GB18030");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
	
	try{
		String sre=request.getHeader("referer");
		String arr[]=sre.split("/");
		sre=arr[arr.length-1]; 
		if(request.getParameter("service")==null){
			response.sendRedirect(request.getContextPath()+"/Login.jsp");
		}else{
			String getservice=new String(request.getParameter("service").getBytes("ISO-8859-1"),"UTF-8");
			String service=getservice.replace("\"", "");
			if(service.equals("产品注册")){
				String st="<div id='add'><a href='javascript:void(0)' onclick='openQuestion()'><img src='pic/regadd.png'></img></a></div>";
				GetProductRegister gpr=new GetProductRegister();
				List<String> li=gpr.Check("10000");
				for(int i=0,l=li.size()/6;i<l;i++){
					String s=
							"<div id='registered'>"+
							"<table>"+
							"<tr><td colspan='2' style='border-bottom:1px solid red;' id='tablet'>"+li.get(0+i*7)+"</td></tr>"+
							"<tr><td id='tablel'>Model:</td><td>"+li.get(1+i*7)+"</td></tr>"+
							"<tr><td id='tablel'>PumpNo:</td><td>"+li.get(2+i*7)+"</td></tr>"+
							"<tr><td id='tablel'>CrankCaseNo:</td><td>"+li.get(3+i*7)+"</td></tr>"+
							"<tr><td id='tablel'>MotorNo:</td><td>"+li.get(4+i*7)+"</td></tr>"+
							"<tr><td id='tablel'>PD:</td><td>"+li.get(5+i*7)+"</td></tr>"+
							"<tr><td id='tablel'>RegDate:</td><td>"+li.get(6+i*7)+"</td></tr>"+
							"</table>"+
							"</div>";
							st=st+s;
				}
				out.print(st);		
			}
			if(service.equals("售后申请")){
				String st="<div id='add'><a href='javascript:void(0)' onclick='openQuestion()'><img src='pic/service.png'></img></a></div>";
				out.print(st);		
			}
			if(service.equals("维修申请")){
				String st="<div id='add'><a href='javascript:void(0)' onclick='openQuestion()'><img src='pic/repair.png'></img></a></div>";
				out.print(st);		
			}
			if(service.equals("投诉建议")){
				String st="<div id='add'><a href='javascript:void(0)' onclick='openQuestion()'><img src='pic/advise.png'></img></a></div>";
				out.print(st);		
			}
			if(service.equals("个人信息")){
				String st="<div></div>";
				out.print(st);		
			}
			
		}
	}catch(Exception e){
		response.sendRedirect(request.getContextPath()+"/Login.jsp");
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
