/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-07-13 08:59:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tlweb.*;

public final class CustomCtrl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GB18030");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"webicon.ico\" rel=\"shortcut icon\" />\r\n");
 
	UserInfo uf=new UserInfo();
	String phone="";
	String ses="";
	String uid="";
	String company="";
 	try{
 		phone=request.getParameter("uid");
 		company=uf.getCompany(phone);
		if(session.getAttribute(phone)==null){
			response.sendRedirect("Login.jsp");
		}else{
			ses=session.getAttribute(phone).toString();
		}
	}catch(Exception e){
		response.sendRedirect("Login.jsp");
	} 

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=GB18030\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Css/CustomCtrl.css\">\r\n");
      out.write("<title>用户中心</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"showques\">\r\n");
      out.write("\t\t<div id=\"question\">\r\n");
      out.write("\t\t\t<div id=\"questop\" style=\"width:auto;height:60px;\">\r\n");
      out.write("\t\t\t\t<input  id=\"SN\"\r\n");
      out.write("\t\t\t\tstyle=\"text-align:center;border-radius:5px;border:1px solid #a0b1c4;width:350px;margin:10px;height:40px;float:left;\" \r\n");
      out.write("\t\t\t\tplaceholder=\"请输入设备SN码  例:MF1604060A\" type=\"text\" maxlength=20 onblur=\"checkSN(this)\">\r\n");
      out.write("\t\t\t\t<div id=\"sntip\" style=\"float:left;text-align:left;margin:11px;height:40px;width:auto;font-size:18px; line-height:44px;color:red;\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"close\" style=\"height:24px;width:24px;float:right;margin-right:5px;margin-top:5px;\"><a href='javascript:void(0)' onclick=\"closeQuestion()\"><img src=\"pic/close.png\"></a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"clear:both;margin-top:20px;\">\r\n");
      out.write("\t\t\t\t<table cellspacing=\"5\">\r\n");
      out.write("\t\t\t\t\t<tr><td><h4>安装要求</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td>1.请按照安装图纸安装 2.供水管路需满足产品流量 3.电路需具备从业资格人员安装</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><h4>使用要求</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td>1.请仔细阅读本产品使用说明书 2.使用过程中严禁违规操作 3.请确保操作人员已明确知晓重要安全说明</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><h4>保修事项</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td>1.对于违规操作产生的故障不予以保修 2.保修起始日期为注册日期 3.如注册日期与出厂日期相差15日按出厂日期计算保修日期</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><h4>其他事项</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td>1.收货前请与经销商确认出厂日期 2.保修详细：电机及泵保修365日；电器、电气设备保修30日</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr></tr>\r\n");
      out.write("\t\t\t\t\t<tr></tr>\r\n");
      out.write("\t\t\t\t\t<tr></tr>\r\n");
      out.write("\t\t\t\t\t<tr></tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<tr><td><input  type=\"checkbox\" id=\"agreement\" onclick=\"checkUserAgree(this)\">已仔细阅读上述要求,并同意遵守</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input id=\"registerB\" style=\"position:absolute; border:0px;color:white;font-size:20px;border-radius:3px;\r\n");
      out.write("\t\t\twidth:300px;height:45px;background-color:gray;left:300px;bottom:30px;\" type=\"button\"  value=\"注册\" onmousemove=\"getFocus()\" disabled=true>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<a href=\"index.html\">天澜清洗设备有限公司用户平台</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<div id=\"all\">\r\n");
      out.write("\t\t\t<div id=\"sec\">\r\n");
      out.write("\t\t\t\t<div id=\"left\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align:center;\" colspan=\"2\">");
      out.print(company );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"lef\">星级:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>暂无</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"lef\">信用:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>暂无</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"lef\">积分:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>暂无</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align:center;\" colspan=\"2\"><a style=\"text-decoration:none;color:black;\" href=\"#\">业务记录</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"right\">\r\n");
      out.write("\t\t\t\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"indexList\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a style=\"border:0px;color:white;background:#00a2e9;\"  href=\"javascript:void(0)\"  onclick='selectservice(this)'>产品注册</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0)\" onclick='selectservice(this)'>售后申请</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0)\" onclick='selectservice(this)'>维修申请</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0)\" onclick='selectservice(this)'>投诉建议</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:void(0)\" onclick='selectservice(this)'>个人信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"center\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("var start=createRequest('AjaxJs/ReturnService.jsp?service='+encodeURI(\"产品注册\")+'&datetime='+new Date().getTime());\r\n");
      out.write("function createRequest(url) {\r\n");
      out.write("    http_request = false;\r\n");
      out.write("    if (window.XMLHttpRequest) {    \t\t\t\t\t\t\t   // 非IE浏览器\r\n");
      out.write("        http_request = new XMLHttpRequest();\t                      //创建XMLHttpRequest对象\r\n");
      out.write("    } else if (window.ActiveXObject) {     \t\t\t\t\t\t   // IE浏览器\r\n");
      out.write("        try {\r\n");
      out.write("            http_request = new ActiveXObject(\"Msxml2.XMLHTTP\");\t   //创建XMLHttpRequest对象\r\n");
      out.write("        } catch (e) {\r\n");
      out.write("            try {\r\n");
      out.write("                http_request = new ActiveXObject(\"Microsoft.XMLHTTP\");  //创建XMLHttpRequest对象\r\n");
      out.write("           } catch (e) {}\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    if (!http_request) {\r\n");
      out.write("        alert(\"不能创建XMLHttpRequest对象实例！\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    http_request.onreadystatechange = getResult;\t\t\t\t\t   //调用返回结果处理函数\r\n");
      out.write("    http_request.open('GET', url, true);\t\t\t\t\t\t\t   //创建与服务器的连接\r\n");
      out.write("    http_request.send(null);\t\t\t\t\t\t\t\t\t   //向服务器发送请求\r\n");
      out.write("}\r\n");
      out.write("function getResult() {\r\n");
      out.write("    if (http_request.readyState == 4) {     \t\t// 判断请求状态\r\n");
      out.write("        if (http_request.status == 200) {     \t\t// 请求成功，开始处理返回结果\r\n");
      out.write("            document.getElementById(\"center\").innerHTML=http_request.responseText;\t//设置提示内容\r\n");
      out.write("            //alert(http_request.responseText);\r\n");
      out.write("           // document.getElementById(\"toolTip\").style.display=\"block\";\t//显示提示框\r\n");
      out.write("        } else {     \t\t\t\t\t\t// 请求页面有错误\r\n");
      out.write("            alert(\"您所请求的页面有错误！\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function openQuestion(){  //打开绑定div\r\n");
      out.write("\tvar ques=document.getElementById(\"question\");\r\n");
      out.write("\tques.style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("function closeQuestion(){   //关闭绑定div\r\n");
      out.write("\tvar ques=document.getElementById(\"question\");\r\n");
      out.write("\tques.style.display=\"none\";\r\n");
      out.write("}\r\n");
      out.write("function selectservice(obj){\r\n");
      out.write(" \tvar liarr=document.getElementById(\"indexList\").getElementsByTagName(\"a\");\r\n");
      out.write("\tfor(i=0;i<liarr.length;i++){  //清空选中样式\r\n");
      out.write("\t\tliarr[i].style.backgroundColor=\"white\";  \r\n");
      out.write("\t\tliarr[i].style.color=\"#00a2e9\";\r\n");
      out.write("\t} \r\n");
      out.write("\t//设置选中样式\r\n");
      out.write("\tobj.style.backgroundColor = \"#00a2e9\";\r\n");
      out.write("\tobj.style.color=\"white\";\r\n");
      out.write("\tvar str=JSON.stringify(obj.innerHTML);\r\n");
      out.write("\tcreateRequest(\"AjaxJs/ReturnService.jsp?service=\"+encodeURI(str)+\"&datetime=\"+new Date().getTime());\r\n");
      out.write("\t//alert(str);\r\n");
      out.write("}\r\n");
      out.write("function checkUserAgree(obj){\r\n");
      out.write("\tif(obj.checked){\r\n");
      out.write("\t\tdocument.getElementById(\"registerB\").disabled=false; \r\n");
      out.write("\t\tdocument.getElementById(\"registerB\").style.backgroundColor=\"#5a98de\";\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdocument.getElementById(\"registerB\").disabled=true; \r\n");
      out.write("\t\tdocument.getElementById(\"registerB\").style.backgroundColor=\"gray\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function getFocus(){\r\n");
      out.write("\tdocument.getElementById(\"registerB\").focus();\r\n");
      out.write("}\r\n");
      out.write("function createCheckSNRequest(url) {\r\n");
      out.write("    http_request = false;\r\n");
      out.write("    if (window.XMLHttpRequest) {    \t\t\t\t\t\t\t   // 非IE浏览器\r\n");
      out.write("        http_request = new XMLHttpRequest();\t                      //创建XMLHttpRequest对象\r\n");
      out.write("    } else if (window.ActiveXObject) {     \t\t\t\t\t\t   // IE浏览器\r\n");
      out.write("        try {\r\n");
      out.write("            http_request = new ActiveXObject(\"Msxml2.XMLHTTP\");\t   //创建XMLHttpRequest对象\r\n");
      out.write("        } catch (e) {\r\n");
      out.write("            try {\r\n");
      out.write("                http_request = new ActiveXObject(\"Microsoft.XMLHTTP\");  //创建XMLHttpRequest对象\r\n");
      out.write("           } catch (e) {}\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    if (!http_request) {\r\n");
      out.write("        alert(\"不能创建XMLHttpRequest对象实例！\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    http_request.onreadystatechange = getResult;\t\t\t\t\t   //调用返回结果处理函数\r\n");
      out.write("    http_request.open('GET', url, true);\t\t\t\t\t\t\t   //创建与服务器的连接\r\n");
      out.write("    http_request.send(null);\t\t\t\t\t\t\t\t\t   //向服务器发送请求\r\n");
      out.write("}\r\n");
      out.write("function getCheckSNResult() {\r\n");
      out.write("    if (http_request.readyState == 4) {     \t\t// 判断请求状态\r\n");
      out.write("        if (http_request.status == 200) {     \t\t// 请求成功，开始处理返回结果\r\n");
      out.write("            document.getElementById(\"sntip\").innerHTML=http_request.responseText;\t//设置提示内容\r\n");
      out.write("            //alert(http_request.responseText);\r\n");
      out.write("           // document.getElementById(\"toolTip\").style.display=\"block\";\t//显示提示框\r\n");
      out.write("        } else {     \t\t\t\t\t\t// 请求页面有错误\r\n");
      out.write("            alert(\"您所请求的页面有错误！\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function checkSN(obj){\r\n");
      out.write("\tvar regex =/^MF[0-9]{8}[A-Z]$/;\r\n");
      out.write("\tif(obj.value==\"\"){\r\n");
      out.write("\t\tdocument.getElementById(\"sntip\").innerHTML=\"请输入序列号\";\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tif(regex.test(obj.value)){\r\n");
      out.write("\t\t\tcreateCheckSNRequest(\"AjaxJs/CheckSN?sn=\"+encodeURI(obj.value)+\"&datetime=\"+new Date().getTime());\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById(\"sntip\").innerHTML=\"序列号格式错误，请核对\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
