/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-07-14 03:16:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GB18030");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"webicon.ico\" rel=\"shortcut icon\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=GB18030\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Css/Login.css\">\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("\tfunction createLogin(url) {\r\n");
      out.write("\t    http_request = false;\r\n");
      out.write("\t    if (window.XMLHttpRequest) {    \t\t\t\t\t\t\t   // 非IE浏览器\r\n");
      out.write("\t        http_request = new XMLHttpRequest();\t                      //创建XMLHttpRequest对象\r\n");
      out.write("\t    } else if (window.ActiveXObject) {     \t\t\t\t\t\t   // IE浏览器\r\n");
      out.write("\t        try {\r\n");
      out.write("\t            http_request = new ActiveXObject(\"Msxml2.XMLHTTP\");\t   //创建XMLHttpRequest对象\r\n");
      out.write("\t        } catch (e) {\r\n");
      out.write("\t            try {\r\n");
      out.write("\t                http_request = new ActiveXObject(\"Microsoft.XMLHTTP\");  //创建XMLHttpRequest对象\r\n");
      out.write("\t           } catch (e) {}\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t    if (!http_request) {\r\n");
      out.write("\t        alert(\"不能创建XMLHttpRequest对象实例！\");\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    http_request.onreadystatechange = getLoginResult;\t\t\t\t\t   //调用返回结果处理函数\r\n");
      out.write("\t    http_request.open('get', url, true);\t\t\t\t\t\t\t   //创建与服务器的连接\r\n");
      out.write("\t    http_request.send(null);\t\t\t\t\t\t\t\t\t   //向服务器发送请求\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getLoginResult() {\r\n");
      out.write("\t    if (http_request.readyState == 4) {     \t\t// 判断请求状态\r\n");
      out.write("\t        if (http_request.status == 200) {     \t\t// 请求成功，开始处理返回结果\r\n");
      out.write("\t        \tvar restr=http_request.responseText;\r\n");
      out.write("\t        \tvar str=JSON.stringify(restr);\r\n");
      out.write("\t        \t//alert(str);\r\n");
      out.write("\t        \tif(str.indexOf(\"success\")>0){\r\n");
      out.write("\t        \t\tvar user=document.getElementById(\"usern\").value;\r\n");
      out.write("\t        \t\twindow.location.href='CustomCtrl.jsp?uid='+encodeURI(user)+'&datetime='+new Date().getTime();\r\n");
      out.write("\t        \t}else{\r\n");
      out.write("\t        \t\tdocument.getElementById(\"showMessage\").innerHTML=\"用户名或密码错误或账号未激活\";\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        } else {     \t\t\t\t\t\t// 请求页面有错误\r\n");
      out.write("\t            alert(\"您所请求的页面有错误！\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getKey()  {  \r\n");
      out.write("\t   if(event.keyCode==13){  \r\n");
      out.write("\t    \tcheckLogin(); \r\n");
      out.write("\t    }     \r\n");
      out.write("\t} \r\n");
      out.write(" \tfunction checkLogin(){\r\n");
      out.write(" \t\tvar user=document.getElementById(\"usern\").value;\r\n");
      out.write(" \t\tvar pass=document.getElementById(\"pass\").value;\r\n");
      out.write(" \t\tvar regex =/^1[3|4|5|7|8][0-9]\\d{8}$/;\r\n");
      out.write(" \t\tvar passregex=/^[0-9a-zA-Z@#%^_]{6,16}$/;\r\n");
      out.write(" \t\tvar error=document.getElementById(\"showMessage\").innerHTML;\r\n");
      out.write(" \t\tif(user!=\"\"&&pass!=\"\"){\r\n");
      out.write(" \t\t\tif(regex.test(user)&&passregex.test(pass)){\r\n");
      out.write(" \t\t\t\tif(error!=\"\"){\r\n");
      out.write(" \t \t\t\t\tdocument.getElementById(\"showMessage\").innerHTML=\"\";\r\n");
      out.write(" \t \t\t\t}\r\n");
      out.write(" \t\t\t\tcreateLogin('AjaxJs/CheckLogin.jsp?user='+encodeURI(user)+'&passw='+encodeURI(pass)+'&datetime='+new Date().getTime());\r\n");
      out.write(" \t\t\t}else{\r\n");
      out.write(" \t\t\t\tdocument.getElementById(\"showMessage\").innerHTML=\"用户名或密码格式错误或含有非法字符\";\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t}else{\r\n");
      out.write(" \t\t\tdocument.getElementById(\"showMessage\").innerHTML=\"用户名或密码为空\";\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t}\r\n");
      out.write("</script>\r\n");
      out.write("<title>用户登录</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"login\">\r\n");
      out.write("\t<div id=\"company\"><a href=\"index.html\">天澜公司信息平台</a></div>\r\n");
      out.write("\t<div id=\"showMessage\"></div>\r\n");
      out.write("\t<form action=\"index.html\" method=\"post\" name=\"loginform\">\r\n");
      out.write("    <table  align=\"center\">\r\n");
      out.write("    \t<tr>\r\n");
      out.write("        <td><input type=\"text\" id=\"usern\" maxlength=\"40\" placeholder=\"现仅支持手机号登录\"></td>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td><input type=\"password\" id=\"pass\" maxlength=\"40\" onkeyup=\"getKey()\" placeholder=\"请输入密码\"></td>\r\n");
      out.write("        <tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <input type=\"button\" id=\"loginb\" style=\"background-color:#5a98de;\" value=\"登 录\" onclick=\"checkLogin()\">\r\n");
      out.write("    </form>\r\n");
      out.write("    <ul>\r\n");
      out.write("    \t<li><a id=\"right\" href=\"\">忘记密码</a></li>\r\n");
      out.write("        <li><a id=\"right\" href=\"Register.jsp\">注册账号</a></li>\r\n");
      out.write("        <li><a id=\"last\" href=\"\">意见反馈</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
