/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-07-13 03:48:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"webicon.ico\" rel=\"shortcut icon\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>用户注册</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Css/Register.css\">\r\n");
      out.write("<script language=\"javascript\" src=\"Js/Register.js\">\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"regmain\">\r\n");
      out.write("    \t<form>\r\n");
      out.write("        \t<table>\r\n");
      out.write("           \t    <tr>\r\n");
      out.write("                <td style=\" font-size:24px;text-align:center;height:45px;color:#00a2e9;text-shadow: 2px 2px 0px #fff;\" colspan=\"2\">\r\n");
      out.write("                <b><a style=\"font-size:24px;color:#00a2e9;\" href=\"index.html\">天澜用户注册</a></b>\r\n");
      out.write("                </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            \t<tr>\r\n");
      out.write("            \t<td class=\"rtb\">用户名:</td>\r\n");
      out.write("            \t<td><input type=\"text\" id=\"usert\" class=\"regt\" maxlength=\"20\" onblur=\"checkUser()\" placeholder=\"仅支持手机注册\">\r\n");
      out.write("            \t*</td>\r\n");
      out.write("            \t</tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div class=\"tip\" id=\"showtip\"></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td class=\"rtb\">密码:</td><td><input type=\"password\" id=\"passt1\" class=\"regt\" maxlength=\"20\" onblur=\"checkPass()\" placeholder=\"请输入密码\">\r\n");
      out.write("                *</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div class=\"tip\"  id=\"showpass1\"></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td class=\"rtb\">确认密码:</td>\r\n");
      out.write("                <td><input type=\"password\" id=\"passt2\" class=\"regt\" maxlength=\"20\" onkeyup=\"equalsPass()\" placeholder=\"请确认密码\">\r\n");
      out.write("                *</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div class=\"tip\"  id=\"showpass2\"></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td class=\"rtb\">公司(店)名称:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                <input type=\"text\" id=\"company\" class=\"regt\" maxlength=\"40\" onblur=\"checkStr(this.value,'companytip')\"  placeholder=\"请填写真实店名\">\r\n");
      out.write("                *</td\r\n");
      out.write("                ></tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div class=\"tip\" id=\"companytip\"></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr><td class=\"rtb\">行业:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                <select id=\"hy\">\r\n");
      out.write("                \t<option>选择行业</option>\r\n");
      out.write("                    <option>美容</option>\r\n");
      out.write("                    <option>养殖</option>\r\n");
      out.write("                    <option>化工</option>\r\n");
      out.write("                    <option>电子</option>\r\n");
      out.write("                    <option>海事</option>\r\n");
      out.write("                    <option>煤矿</option>\r\n");
      out.write("                    <option>农业</option>\r\n");
      out.write("                    <option>市政</option>\r\n");
      out.write("                    <option>环卫</option>\r\n");
      out.write("                    <option>五金</option>\r\n");
      out.write("                    <option>造船</option>\r\n");
      out.write("                    <option>物业</option>\r\n");
      out.write("                    <option>其他</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                *</td></tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div  class=\"tip\" ></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td class=\"rtb\">联系人:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                <input type=\"text\" id=\"contactt\" class=\"regt\" maxlength=\"20\" onblur=\"checkStr(this.value,'contacttip')\" placeholder=\"请填写真实姓名\">\r\n");
      out.write("                *</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div class=\"tip\" id=\"contacttip\"></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr><td class=\"rtb\">职位:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                <select id=\"zw\">\r\n");
      out.write("                \t<option>选择职位</option>\r\n");
      out.write("                    <option>企业所有人</option>\r\n");
      out.write("                    <option>经理</option>\r\n");
      out.write("                    <option>店长</option>\r\n");
      out.write("                    <option>主管</option>\r\n");
      out.write("                    <option>职员</option>\r\n");
      out.write("                    <option>操作员</option>\r\n");
      out.write("                    <option>其他</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                *</td></tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div  class=\"tip\" ></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr><td class=\"rtb\">国家:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                <select id=\"country\" onchange=\"getProvince(this.value)\">\r\n");
      out.write("                \t<option>请选择国家</option>\r\n");
      out.write("                \t<option value=\"中国\">中国</option>\r\n");
      out.write("                \t<option>越南</option>\r\n");
      out.write("                \t<option>新加坡</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                *</td></tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div  class=\"tip\" ></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr><td class=\"rtb\">省份:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                <select id=\"province\" onchange=\"getCity(this.value)\">\r\n");
      out.write("                \t<option>请选择省份</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                *</td></tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div  class=\"tip\" ></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr><td class=\"rtb\">选择城市:</td>\r\n");
      out.write("                <td  >\r\n");
      out.write("                <select id=\"city\">\r\n");
      out.write("                \t<option>请选择城市</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                *</td></tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div  class=\"tip\" ></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td class=\"rtb\">详细地址:</td>\r\n");
      out.write("                <td><input type=\"text\" id=\"daddt\" maxlength=\"100\" class=\"regt\" onblur=\"checkStr(this.value,'addresstip')\" placeholder=\"例:XX区(市，县)XX街道XX号;请勿使用标点符号\">\r\n");
      out.write("                *</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td></td><td><div class=\"tip\" id=\"addresstip\"></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td style=\" text-align:center;\" colspan=\"2\"><input type=\"checkbox\" id=\"agreement\" onclick=\"checkUserAgree(this)\">我同意\r\n");
      out.write("                <a href=\"agreement/UserAgreement.html\" target=\"view_window\">《用户注册协议》</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td style=\" text-align:center;\" colspan=\"2\"><input type=\"button\" id=\"registerB\"  onclick=\"registerID()\" onmousemove=\"getFocus()\" value=\"注册\" disabled=true></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                <p><b>\r\n");
      out.write("                                      请保证注册信息真实有效，如填写虚假信息本公司有权拒绝服务。\r\n");
      out.write("           \t\t注册后账号暂不可登录，需人工验证激活账号后方可登录。（验证时间:注册时间起三个工作日内）\r\n");
      out.write("                </b></p>\r\n");
      out.write("                </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
